---
kind: pipeline
name: default-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag

- name: docker-publish-dev
  pull: default
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: cnrancher/network-controller
    tag: dev
    username:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push

- name: github_binary_release
  pull: default
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "artifacts/templates/*"
  when:
    event:
    - tag

- name: docker-publish
  pull: default
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: cnrancher/network-controller
    tag: "${DRONE_TAG}"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

node:
  instance: agent-amd64
...
