---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod2
  labels:
    app: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: static-macvlan-cni-cfg
    macvlan.pandaria.cattle.io/ip: auto
    macvlan.pandaria.cattle.io/subnet: eth0.100
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600000000"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
---
