apiVersion: v1
kind: Pod
metadata:
  name: samplepod1
  labels:
    app: samplepod
  annotations:
    static-ip: 192.168.56.101/24
    k8s.v1.cni.cncf.io/networks: static-macvlan-cni
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600000000"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
