---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod1
  labels:
    app: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: static-macvlan-cni
    static-ip: 192.168.1.100/24
    static-mac: 0a:00:27:00:00:00
    vlan: mv1.100
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600000000"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
---
