---
apiVersion: "macvlan.cluster.cattle.io/v1"
kind: MacvlanSubnet
metadata:
  name: eth0.100
  namespace: kube-system
spec:
  master: "eth0"
  vlan: 100
  cidr: "192.168.1.0/24"
  mode: "bridge"
  ranges:
  -
    start: "192.168.1.10"
    end: "192.168.1.20"
  -
    start: "192.168.1.30"
    end: "192.168.1.40"
---
