#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

if [ ! -e bin/network-controller ]; then
    ./scripts/build
fi

docker build -f package/Dockerfile -t cnrancher/network-controller .
