#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

if [ ! -e bin/network-controller ]; then
    ./scripts/build
fi

mkdir -p dist/artifacts
cd bin/
tar cvzf ../dist/artifacts/network-controller-${VERSION}.tar.gz .

echo "Built network-controller-${VERSION}.tar.gz"