#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

if [ ! -e bin/static-pod-controller ]; then
    ./scripts/build
fi

mkdir -p dist/artifacts
cd bin/
tar cvzf ../dist/artifacts/static-pod-controller-${VERSION}.tar.gz .

echo "Built static-pod-controller-${VERSION}.tar.gz"