---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: macvlanips.macvlan.cluster.cattle.io
spec:
  group: macvlan.cluster.cattle.io
  version: v1
  scope: Namespaced
  names:
    plural: macvlanips
    singular: macvlanip
    kind: MacvlanIP
    shortNames:
    - macvlanip
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            subnet:
                 type: string
            podId:
                 type: string
            cidr:
                 type: string
            mac:
                 type: string          

  additionalPrinterColumns:
  - name: Subnet
    type: string
    JSONPath: .spec.subnet
  - name: PodId
    type: string
    JSONPath: .spec.podId
  - name: CIDR
    type: string
    JSONPath: .spec.cidr
  - name: MAC
    type: string
    JSONPath: .spec.mac
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: macvlansubnets.macvlan.cluster.cattle.io
spec:
  group: macvlan.cluster.cattle.io
  version: v1
  names:
    kind: MacvlanSubnet
    plural: macvlansubnets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            master:
                 type: string
            vlan:
                 type: integer
            cidr:
                 type: string
            mode:
                 type: string
            gateway:
                  type: string
            ranges:
                type: array
                items:
                  type: object
                  properties:
                    rangeStart:
                      type: string
                    rangeEnd:
                      type: string

  additionalPrinterColumns:
  - name: Master
    type: string
    JSONPath: .spec.master
  - name: VLAN
    type: integer
    JSONPath: .spec.vlan
  - name: CIDR
    type: string
    JSONPath: .spec.cidr
  - name: Mode
    type: string
    JSONPath: .spec.mode
  - name: Gateway
    type: string
    JSONPath: .spec.gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-controller
  namespace: kube-system
  labels:
    app: network-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-controller
  template:
    metadata:
      namespace: kube-system
      labels:
        app: network-controller
    spec:
      serviceAccountName: multus
      containers:
      - image: wardenlym/network-controller:v0.2.1
        name: network-controller
---