---
apiVersion: v1
kind: Pod
metadata:
  name: static-pod-controller
  namespace: kube-system
spec:
  containers:
  - image: wardenlym/static-pod-controller:v0.1.0
    name: static-pod-controller
  restartPolicy: Always
  serviceAccountName: multus
---
